# This settings in this config are known to produce a well-tuned llama-7b model on the Alpaca dataset.

# Model arguments
model_name_or_path: EleutherAI/pythia-70m #bigcode/starcoderbase

# Data training arguments
block_size: 1024
dataset_name: HuggingFaceH4/oasst1_en
dialogue_template: no_system
preprocessing_num_workers: 12

# Training arguments with sensible defaults
# Add other options from here: https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/trainer#transformers.TrainingArguments
bf16: true # Gives ~2x speed up in training time, but disable if you start seeing NaNs
do_eval: true
do_train: true
evaluation_strategy: epoch # One of ["no", "steps", "epoch"]
fp16: false # Gives ~2x speed up in training time, but disable if you start seeing NaNs
gradient_accumulation_steps: 8
gradient_checkpointing: true # Typically halves GPU vRAM used
hub_model_id: HuggingFaceH4/starchat
hub_private_repo: true
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: passive
logging_steps: 8
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 3
output_dir: data/starchat
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false # Only push serious runs to the Hub
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_steps: 500
save_strategy: steps
save_total_limit: null
seed: 42
tf32: true
wandb_run_group: starchat # Name of the W&B group to collect all runs of this experiment under. Use double-digits for {idx}, starting from 00.
wandb_run_id: null # Set this to a globally unique string if you want a descriptive name of your run
wandb_tags: # Use tags to filter runs on WandB
- ift
warmup_ratio: 0.03
weight_decay: 0.